require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "test/fixtures/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "app/views/**/*"
    - "config/environments/*"
    - "node_modules/**/*"

Metrics/MethodLength:
  Description: "Avoid methods longer than 24 lines of code."
  Max: 24

Metrics/ClassLength:
  Description: "Avoid classes longer than 100 lines of code."
  Max: 100
  Enabled: true

Metrics/ModuleLength:
  Description: "Avoid modules longer than 100 lines of code."
  Max: 100
  Enabled: true

Metrics/ParameterLists:
  Description: "Pass no more than four parameters into a method."
  Max: 4
  Enabled: true

Rails/DynamicFindBy:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
